#!/bin/bash

if [[ $1 == "-v" ]]
then
    verbose=true
else
    verbose=false
fi

if [[ $EUID != 0 ]];
then
    echo -e "\e[1;31m==> \e[97mNot running as root. Please run this command as root or with sudo."
    exit 1
fi

echo -e "\e[32m==> \e[1;97mStarting up..." 
sleep 2
echo -e "\e[34m-> \e[1;97mLooking for lsblk." 
sleep 2
lsblkinstall=$(which lsblk)

if [[ $lsblkinstall == "" ]]
then


    if [[ $verbose == true ]]
    then
        echo -e "\e[1A\e[K\e[1;31m==> \e[97mlsblk command not found. Make sure you have the util-linux package installed."
        exit 2
    fi
fi
if [[ $verbose == true ]]
then
    echo -e "\e[1A\e[K\e[1;32m==> \e[97mlsblk found."

    echo -e "\e[1;32m==> \e[97mScanning disks."
fi

hasnvme=$(lsblk -A -N)

hasscsi=$(lsblk -A -S)

sleep 3

if [[ $hasnvme != "" ]]
then 

    if [[ -f "/tmp/diskoutputnvme.json" ]]
    then

        rm /tmp/diskoutputnvme.json
    fi
    lsblk -A -J  -N > /tmp/diskoutputnvme.json

fi

if [[ $hasscsi != "" ]]
then

    if [[ -f "/tmp/diskoutputscsi.json" ]]
    then

        rm /tmp/diskoutputscsi.json
    fi

    lsblk -A -J  -S > /tmp/diskoutputscsi.json

fi
if [[ $verbose == true ]]
then
     echo -e "\e[1A\e[K\e[1;32m==> \e[97mDone. Launching executable..."
     sleep 2
     ./main/p-unlock
fi  