#!/bin/bash

if [[ $1 == "-v" ]]
then
    verbose=true
else
    verbose=false
fi

if [[ $EUID != 0 ]];
then
    echo -e "\e[1;31m==> \e[97mNot running as root. Please run this command as root or with sudo."
    exit 1
fi

echo -e "\e[32m==> \e[1;97mStarting up..."

if [[ $verbose == true ]]
then
    echo -e "  \e[1;34m-> \e[97mLocating Go installation..."
fi

goinstall=$(which go)

if [[ $goinstall == "" ]]
then
    if [[ $verbose == true ]]
    then
        echo -e "\e[1;31m==> \e[97mGo installation not found. Please install the go package and try again."
        exit 2
    fi
fi
if [[ $verbose == true ]]
then
    echo -e "\e[1;32m==> \e[97mGo installation found."

    echo -e "  \e[1;34m-> \e[97mScanning disks."
fi
if [[ $verbose == true ]]
then
    echo -e "  \e[1;34m-> \e[97mLocating SSDs..."
fi  
ssds=$(ls /dev | grep "sd[a-z]")

if [[ $verbose == true ]]
then
     echo -e "\e[1;32m==> \e[97mDone."
fi  

if [[ $verbose == true ]]
then
    echo -e "  \e[1;34m-> \e[97mLocating HDDs..."
fi  

hdds=$(ls /dev | grep "hd[a-z]")

if [[ $verbose == true ]]
then
     echo -e "\e[1;32m==> \e[97mDone."
fi  



for i in $ssds
do
    echo $i
done

for i in $hdds
do
    echo $i
done